name: CBD Blog
description: 好记性不如烂笔头,站在岸上学不会游泳
url: https://icbd.github.io
baseurl: ""
avatar: /images/avatar.jpg
favicon: /images/avatar.jpg
destination: docs
navigation:
  - name: 首页
    url: /
  - name: 归档
    url: /archive
  - name: 关于
    url: /about
paginate: 10
excerpt_separator: <!-- more -->
footer-links:
  twitter: CbdFocus
  github: icbd
  email: wwwicbd@gmail.com
  linkedin:
  rss: icbd

footer-text: Copyright (c) 2020 CBD Blog
#disqus: "cbd-blog"
utteranc:
  repo:  icbd/blogs
  label: utteranc
google_analytics: G-F7YBKQTGB6
permalink: /:title/
paginate_path: /page:num/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :expanded
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# shortcut variables:
# {{ site.vars.key }}
vars:
  sp: |
    <span style="display: inline-block; width: 1em">&nbsp;</span>
  sp2: |
    <span style="display: inline-block; width: 2em">&nbsp;</span>
  sp4: |
    <span style="display: inline-block; width: 4em">&nbsp;</span>
  sub-block-open: |
    <div align="right"><div align="left" style="display: inline-block; width: calc(100% - 4em);margin: 0px;">
  sub-block-close: |
    </div></div>